-- noinspection SqlNoDataSourceInspectionForFile

CREATE SCHEMA SDR;

CREATE TABLE SDR.USER (
  USER_ID NUMBER AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR2(50),
  LAST_NAME VARCHAR2(50),
  EMAIL VARCHAR2(50),
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP
);

CREATE TABLE SDR.`ORDER` (
  ORDER_ID NUMBER AUTO_INCREMENT PRIMARY KEY,
  USER_ID NUMBER,
  TOTAL_PRICE NUMBER,
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP
);

CREATE TABLE SDR.ORDER_ITEM (
  ORDER_ID NUMBER NOT NULL,
  ITEM_ID NUMBER,
  QUANTITY NUMBER,
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP
);

CREATE TABLE SDR.ITEM (
  ITEM_ID NUMBER AUTO_INCREMENT PRIMARY KEY,
  ITEM_NAME VARCHAR2(50),
  DESCRIPTION VARCHAR2(50),
  PRICE NUMBER,
  CREATED_AT TIMESTAMP,
  UPDATED_AT TIMESTAMP
);